#!/bin/bash
CIDdir=/etc/CAT-BOT && [[ ! -d ${CIDdir} ]] && mkdir ${CIDdir}
DIRSCRIPT=/etc/cat/script && [[ ! -d ${DIRSCRIPT} ]] && mkdir -p ${DIRSCRIPT}
DIRSCRIPTC=/etc/cat/casita && [[ ! -d ${DIRSCRIPTC} ]] && mkdir -p ${DIRSCRIPTC}
DIR="/etc/http-shell"
IVAR="/etc/http-instas"
sudo mkdir -p /bin/ejecutar

colores="$(pwd)/colores"
rm -rf ${colores}
wget -O ${colores} "https://raw.githubusercontent.com/darnix1/UDP-Custom/main/colores" &>/dev/null
[[ ! -e ${colores} ]] && exit
chmod +x ${colores} &>/dev/null
source ${colores}



    rm -rf .bash_history
    check_ip
    clear
    [[ ! -d ${IVAR} ]] && touch ${IVAR}
    wget -O /bin/http-server.sh https://www.dropbox.com/s/5l7zbkfj401syfa/http-server.py &>/dev/null
    chmod +x /bin/http-server.sh
    msgi -bar
    os_system
    msgi -ama "$distro $vercion"
    echo "$distro $vercion" > /etc/CAT-BOT/system
   msg -bar
msg -verm " INSTALACION DE PAQUETES "
msg -bar
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Update"
apt-get update &>/dev/null & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Upgrade"
apt-get upgrade -y &>/dev/null & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Ssh"
apt-get install sshpass -y &>/dev/null & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Unzip"
apt-get install unzip -y &>/dev/null & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Zip"
apt-get install zip -y &>/dev/null & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Lsof"
apt-get install lsof >/dev/null 2>&1 & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Sudo"
apt-get install sudo >/dev/null 2>&1 & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Screen"
apt-get install screen -y >/dev/null 2>&1 & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Bc"
apt-get install bc -y >/dev/null 2>&1 & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Netcat"
apt-get install netcat -y >/dev/null 2>&1 & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Jq"
apt-get install jq -y >/dev/null 2>&1 & spiner
echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Apache2"
apt-get install apache2 -y &>/dev/null & spiner
sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1 &
    echo -e "DESCARGANADO LA BASE DEL SERVIDOR FTP"
    
    #EMPIEZA A DESCARGAR LATAM
    mxofc=https://www.dropbox.com/s/3ujxegx15hoh1w2/SCRIPT-LATAM.zip
    mxofca=https://www.dropbox.com/s/o3wyvhaxxb5sj8h/SCRIPTMX.zip
	wget $mxofc &>/dev/null
    wget $mxofca &>/dev/null
	unzip SCRIPT-LATAM.zip &>/dev/null
    unzip SCRIPTMX.zip &>/dev/null

    cp SCRIPT-LATAM/* ${DIRSCRIPT}
    cp SCRIPT/* ${DIRSCRIPTC}
    [[ ! -e ${DIRSCRIPT}/ID.txt ]] && touch ${DIRSCRIPT}/ID.txt
    [[ ! -e ${DIRSCRIPTC}/ID.txt ]] && touch ${DIRSCRIPTC}/ID.txt

    chmod +x ${DIRSCRIPT}/*
    chmod +x ${DIRSCRIPTC}/*

    rm -rf SCRIPT-LATAM.zip
    rm -rf SCRIPT-LATAM
    rm -rf SCRIPTMX.zip
    rm -rf SCRIPT
    
    
    sleep 1s
    echo -e "$bar"
    msgi -verm " DESCARGANDO ARCHIVOS BOT LATAM"
    echo -e "$bar"
    sleep 2s

    echo "menu.sh LATAMbot.sh PDirect.py PGet.py POpen.py PPriv.py PPub.py message.txt" > /etc/newadm-instal
    echo "ID.txt slowdns.sh ADMbot.sh C-SSR.sh Crear-Demo.sh PDirect.py PGet.py POpen.py PPriv.py PPub.py apacheon.sh blockBT.sh budp.sh dns-netflix.sh dropbear.sh fai2ban.sh message.txt openvpn.sh paysnd.sh ports.sh sockspy.sh speed.py squid.sh squidpass.sh ssl.sh tcp.sh ultrahost v2ray.sh python.py" > /etc/newadm-install
echo " DESCARGA FINALIZADA"
    read -p "enter"
    rm -rf .bash_history
    bot_gen
